---
- name: Update dependencies and generate changelog
  hosts: localhost
  gather_facts: false
  vars_files:
    - dependency_config.json
  roles:
    - role: vdd_dependency_manager
      vars:
        debug_mode: true
        pom_file: "./pom.xml"
        changelog_path: "CHANGELOG.md" 