---
- name: Update Python Dependencies
  hosts: localhost
  gather_facts: false
  vars:
    requirements_file: "requirements.txt"
    changelog_path: "CHANGELOG.md"
    debug_mode: true
    dependency_config: "{{ lookup('file', 'dependency_config.json') | from_json }}"
    config_global: "{{ dependency_config.global }}"

  pre_tasks:
    - name: Validate dependency_config.json exists
      stat:
        path: "dependency_config.json"
      register: config_file
      failed_when: not config_file.stat.exists

  roles:
    - vdd_pip_manager 