---
- name: "1. Validate required inputs"
  assert:
    that:
      - config_global.python_dependencies is defined
      - config_global.release_version    is defined
      - config_global.release_date       is defined
    fail_msg: "Missing required key(s) in dependency_config.json"

- name: "2. Ensure requirements.txt exists"
  file:
    path: "{{ requirements_file }}"
    state: touch

- name: "3. Update each dependency in requirements.txt"
  replace:
    path: "{{ requirements_file }}"
    regexp: '^({{ item.name }})==.*$'
    replace: '\1=={{ item.version }}'
    backup: false
  loop: "{{ config_global.python_dependencies }}"
  register: replace_results

- name: "4. Build list of actually updated packages"
  set_fact:
    updated_packages: >-
      {{ replace_results.results
         | selectattr('changed')
         | map(attribute='item')
         | list
      }}

- name: "5. DEBUG: show which packages changed"
  debug:
    var: updated_packages
  when: debug_mode

- name: "6. Stat CHANGELOG.md"
  stat:
    path: "{{ changelog_path }}"
  register: changelog_stat

- name: "7. Create skeleton CHANGELOG.md if missing"
  copy:
    dest: "{{ changelog_path }}"
    backup: false
    content: |
      # Changelog

      All notable changes to this project will be documented in this file.

      ## [Unreleased]

  when: not changelog_stat.stat.exists

- name: "8. Insert release version header"
  lineinfile:
    path: "{{ changelog_path }}"
    insertafter: '^## \[Unreleased\]'
    line: '## [{{ config_global.release_version }}] - {{ config_global.release_date }}'
  when: updated_packages | length > 0

- name: "9. Insert '### Changed' section header"
  lineinfile:
    path: "{{ changelog_path }}"
    insertafter: '^## \[{{ config_global.release_version }}\]'
    line: '### Changed'
  when: updated_packages | length > 0

- name: "10. Insert change bullets"
  lineinfile:
    path: "{{ changelog_path }}"
    insertafter: '^### Changed$'
    line: '- Updated: {{ item.name }} → {{ item.version }}'
  loop: "{{ updated_packages | reverse }}"
  when: updated_packages | length > 0