---
# roles/vdd_pip_manager/tasks/main.yml

- name: "1. Validate required inputs"
  assert:
    that:
      - config_global.python_dependencies is defined
      - config_global.release_version    is defined
      - config_global.release_date       is defined
    fail_msg: "Missing required key(s) in dependency_config.json"

- name: "2. Ensure requirements.txt exists"
  file:
    path: "{{ requirements_file }}"
    state: touch

- name: "3. Update each approved dependency (in-place)"
  replace:
    path: "{{ requirements_file }}"
    regexp: '^({{ item.name | regex_escape }})==.*$'
    replace: '\1=={{ item.version }}'
    backup: false
  loop: "{{ config_global.python_dependencies }}"
  register: replace_results

- name: "4. Build list of actually updated packages"
  set_fact:
    changed_dependencies: >-
      {{ replace_results.results
         | selectattr('changed')
         | map(attribute='item')
         | list
      }}

- name: "5. DEBUG: which dependencies actually changed?"
  debug:
    var: changed_dependencies
  when: debug_mode

- name: "6. Re-render full CHANGELOG.md from template"
  template:
    src: changelog_update.j2
    dest: "{{ changelog_path }}"
    # backup: yes
  vars:
    existing_changelog: "{{ lookup('file', changelog_path, errors='ignore') | default('') }}"